# Generated by Django 5.0.1 on 2025-05-31 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_announcement_read_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='date_added',
            new_name='submitted_at',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'assignment')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='assignment_name',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='max_score',
        ),
    ]
